
require 'rake/testtask'

test_libs = ["../lib", "../../../classico1-bento"]

Rake::TestTask.new do |t|
	t.libs = test_libs
	t.test_files = FileList[%w(
		test1.rb
		db1.rb
		lot1.rb
		cspec1.rb
		project1.rb
		)]
#	t.verbose = true
end

Rake::TestTask.new("test:lot") do |t|
	t.libs = test_libs
	t.test_files = FileList[%w(
		lot1.rb
		)]
end

Rake::TestTask.new("test:project") do |t|
	t.libs = test_libs
	t.test_files = FileList[%w(
		project1.rb
		)]
end

Rake::TestTask.new("test:act") do |t|
	t.libs = test_libs
	t.test_files = FileList[%w(
		activity1.rb
		)]
end
